<article class="article-content">
	<header class="article-header">
		<h2>Politics</h2>
		<p class="date-stamp"><time>Tuesday 4 June 2013 20.42 BST</time></p>
		<h1><a href="#">John Bercow criticised for saying eastern Europeans are harder workers</a></h1>
	</header>
	<figure>
		<img src="../img/image-5x3.svg" />
		<figcaption>
			<p>Jersey, in the Channel Islands, is among overseas territories being asked by the government in Westminster to share tax information. <cite class="image-source">Photograph: Chris Coe</cite></p>
		</figcaption>
	</figure>
	
	<ul class="article-details">
		<li class="author"><strong><a href="#">Patrick Wintour</a></strong>, political editor</li>
	</ul>
	<p>John Bercow, the Speaker of the House of Commons, has been criticised for suggesting that eastern European immigrants have more "aptitude and commitment" to work than British people.</p>
	<p>Bercow made the comments during an official visit last week to the Romanian parliament, where he was asked about the debate in the UK over the lifting of European immigration restrictions on Romanians and Bulgarians at the start of next year.</p>
	<p>While stressing that he believes controls on migration are needed, he also said that immigration had great advantages for the UK and that critics of recent immigration trends had made their case in a "bellicose and strident tone".</p>
	<p>"I believe things should be controlled and monitored when it comes to migration – any state that wants to protect its own people should do this – but there are also great advantages," said Bercow.</p>
	<p><a href="#">Read the full article</a></p>
</article>
<!-- end ajaxed article -->