<article class="article-content">
	<header class="article-header" data-importance="small">
		<h2>Politics</h2>
		<p class="date-stamp"><time>Tuesday 4 June 2013 20.42 BST</time></p>
		<h1><a href="#">Gibraltar tries to lure London hedge fund bosses with promise of low taxes</a></h1>
	</header>
	<figure>
		<img src="../img/image-5x3.svg" />
		<figcaption>
			<p>Jersey, in the Channel Islands, is among overseas territories being asked by the government in Westminster to share tax information. <cite class="image-source">Photograph: Chris Coe</cite></p>
		</figcaption>
	</figure>
	
	<ul class="article-details">
		<li class="author"><strong><a href="#">Patrick Wintour</a></strong>, political editor</li>
	</ul>
	<p>Gibraltar is launching a campaign to persuade hedge funds to ditch their plush Mayfair offices for the low taxes of "the Rock".</p>
	<p>Fabian Picardo, chief minister of the British overseas territory, said multimillionaire hedge fund managers should quit London for Gibraltar because it's "much cheaper", while promotional material promises they are "unlikely to be liable for corporation tax".</p>
	<p>Picardo, who has made attracting hedge funds a key aim of his administration, last week invited hedge fund managers to the peninsula where they were told income tax could be limited to £30,000 a year no matter how many millions they earned.</p>
	<p>Gibraltar also boasts no VAT and social security payments of just £120 per family a month. In the UK the top rate of income tax is 45%, VAT is 20% and national insurance is levied at 14% of weekly earnings above £797.</p>
	<p><a href="#">Read the full article</a></p>
</article>
<!-- end ajaxed article -->