<dl>
	
</dl>
<dt>2.20pm BST</dt>
<dd>
	<p>Andy Burnham, the shadow health secretary, says today's report will have left people "stunned".</p>
	<p>Labour echoes the apology, he says.</p>
	<p>People accept that mistakes get made. But trying to cover up mistakes is inexcusable.</p>
	<p>He pays tribute to the family of Joshua Titcombe, the baby who died at Furness general hospital's maternity unit. Without them, these revelations would never have come out, he says.</p>
	<p>Burnham asks Hunt if he is confident that the cover-up at CQC is no longer happening.</p>
	<p>Is anyone involved in the original decision to delete the critical report still working at the CQC, or in the NHS?</p>
	<p>Was anyone at the Department for Health aware of the deleted report? And was anyone at the department involved in the decision to delete it?</p>
	<p>A whistleblower on the board raised concerns. There was then an attempt to remove her. Were ministers involved in this?</p>
	<figure>
		<img src="../img/video-16x10.svg" />
		<figcaption>Andy Burnham speaking earlier <cite class="image-source">Video: BBC Parliament</cite></figcaption>
	</figure>
</dd>

<dt>2.12pm BST</dt>
<dd>
	<p>Hunt outlines various measures the government is taking to tighten the care regime in hospitals, including measures in the care bill.</p>
	<p>David Cameron has appointed Don Berwick, President Obama's former patient adviser, to produce a report on patient safety, he says.</p>
</dd>

<dt>2.10pm BST</dt>
<dd>
	<p>Hunt says what happened to families at Universities Hospital Morecambe Bay was a tragedy.</p>
	<p>He says he wants to apologise to those families.</p>
	<p>What the Care Quality Commission did was totally unacceptable.</p>
	<p>But there is now new leadership, he says.</p>
	<p>David Prior was appointed chairman in January. He insisted the report into the cover-up was published as soon as possible.</p>
	<p>He wants to turn it into a fearless regulator.</p>
	<p>Prior will report back to Hunt on what action he is taking, including internal disciplinary proceedings.</p>	
</dd>

<dt>2.06pm BST</dt>
<dd>
	<h2>Jeremy Hunt's statement on the CQC cover-up</h2>
	<aside class="article-related left">
		<h2>Reaction</h2>
		<article class="article" data-importance="small">
			<h3><a href="#">NHS watchdog cover-up 'deeply disturbing', says Downing Street</a></h3>
			<p>No 10 condemns cover-up but says government has taken 'very clear, strong action' to reform Care Quality Commission</p>
		</article>
	</aside>
	<p>Jeremy Hunt, the health secretary, is just starting his statement on the GCHQ cover-up.</p>
</dd>

<dt>2.01pm BST</dt>
<dd>
	<p>Asked if the NHS will be included in the US/EU free trade deal, Cameron says he is not aware of a specific exemption. He thinks it will have the same status as it does in trade talks within the EU.</p>
</dd>

<dt>2.00pm BST</dt>
<dd>
	<p>Cameron says there were not specific discussions at the G8 about a no fly zone over Syria. He had various discussions with President Obama about Syria, he says, but there are no plans for a no fly zone.</p>
</dd>