<article class="article-content">
	<header class="article-header">
		<h2>Politics</h2>
		<p class="date-stamp"><time>Tuesday 4 June 2013 20.42 BST</time></p>
		<h1><a href="#">Cameron talks tough – but what can he deliver?</a></h1>
	</header>
	<figure>
		<img src="../img/image-5x3.svg" />
		<figcaption>
			<p>Jersey, in the Channel Islands, is among overseas territories being asked by the government in Westminster to share tax information. <cite class="image-source">Photograph: Chris Coe</cite></p>
		</figcaption>
	</figure>
	
	<ul class="article-details">
		<li class="author"><strong><a href="#">Patrick Wintour</a></strong>, political editor</li>
	</ul>
	<p>The summit of the G8 world leaders in Gleneagles, Scotland, chaired by Tony Blair in 2005 had a very simple agenda: "Drop the debt and hand over the aid." Blair largely succeeded in winning big donor pledges to help Africa, even if many of those pledges subsequently proved worthless (Silvio Berlusconi was especially generous with his promises, but not the Italian chequebook).</p>
<p>Nearly a decade on, as Britain chairs the G8 again later this month in Northern Ireland, the political climate and the intellectual context has changed. Poverty, hunger and the need for aid is still not history. But a mixture of donor fatigue, western austerity, gradual growth in some African economies and the persistence of corruption and inept government in Africa mean some of the old certainties have lapsed.</p>
	<p>David Cameron wants his G8 to focus on "the three Ts" – tax, transparency and trade – as the best way of helping the poor, and righting injustice. He also wants the summit itself in Fermanagh to be less about grand communiques, often built for the shredder, and more about a frank discussion between world leaders about the big issues they collectively face.</p>
	<p>But he also indicated at the turn of the year in a landmark speech at the World Economic Forum in Davos, Switzerland, that he wanted tax – both corporate avoidance and freeloading by the rich – to be at the very top of the agenda, both as a way of filling the Treasury coffers of the west, and stopping the plunder of the resources of the developing world. It is not a modest proposal, requiring both highly technical and political global solutions.</p>
	<p><a href="#">Read the full article</a></p>
</article>
<!-- end ajaxed article -->