<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>17 Apr 2013</time></p>
	<h2><a href="#">Thatcher funeral: Cameron says 'we are all Thatcherites now'</a></h2>
</article>
<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>17 Apr 2013</time></p>
	<h2><a href="#">Steve Bell's If ... on a truly British funeral for Thatcher</a></h2>
</article>
<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>18 Apr 2013</time></p>
	<h2><a href="#">It's time to bury not just Thatcher – but Thatcherism</a></h2>
</article>
<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>17 Apr 2013</time></p>
	<h2><a href="#">Steve Bell on Margaret Thatcher's memorial service – cartoon</a></h2>
</article>
<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>17 Apr 2013</time></p>
	<h2><a href="#">Royal Bank of Scotland should stay in public ownership for now – poll</a></h2>
</article>
<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>16 Apr 2013</time></p>
	<h2><a href="#">Are David and Samantha Cameron Gillian Welch's biggest fans?</a></h2>
</article>
<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>16 Apr 2013</time></p>
	<h2><a href="#">Royal Bank of Scotland should stay in public ownership for now – poll</a></h2>
</article>
<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>16 Apr 2013</time></p>
	<h2><a href="#">Are David and Samantha Cameron Gillian Welch's biggest fans?</a></h2>
</article>
<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>16 Apr 2013</time></p>
	<h2><a href="#">MEPs reject key reform of emissions trading scheme</a></h2>
</article>
<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>16 Apr 2013</time></p>
	<h2><a href="#">Tory MEPs planning to defy David Cameron on key emissions trading vote</a></h2>
</article>	