<article class="article article-sport" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>7 Apr 2013</time></p>
	<h2><a href="#">GB's James Ward and Dan Evans see off Russia and make Davis Cup history</a></h2>
</article>
<article class="article article-sport" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>6 Apr 2013</time></p>
	<h2><a href="#">Jonny Marray and Colin Fleming lift Britain in Davis Cup tie with Russia</a></h2>
</article>
<article class="article article-sport" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>5 Apr 2013</time></p>
	<h2><a href="#">Britain trail 2-0 to Russia in Davis Cup after heroic Dan Evans effort</a></h2>
</article>
<article class="article article-sport" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>4 Apr 2013</time></p>
	<h2><a href="#">Andy Murray signs deal that brings IPL-style tennis event a step closer</a></h2>
</article>
<article class="article article-sport" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>3 Apr 2013</time></p>
	<h2><a href="#">Laura Robson beaten by Eugenie Bouchard in three sets in Charleston</a></h2>
</article>
<article class="article article-sport" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>4 Apr 2013</time></p>
	<h2><a href="#">Andy Murray signs deal that brings IPL-style tennis event a step closer</a></h2>
</article>
<article class="article article-sport" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>3 Apr 2013</time></p>
	<h2><a href="#">Laura Robson beaten by Eugenie Bouchard in three sets in Charleston</a></h2>
</article>
<article class="article article-sport" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>3 Apr 2013</time></p>
	<h2><a href="#">British No2 Heather Watson is diagnosed with glandular fever</a></h2>
</article>
<article class="article article-sport" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>2 Apr 2013</time></p>
	<h2><a href="#">Laura Robson leaves Spaniard chasing shadows in Charleston opener</a></h2>
</article>
<article class="article article-sport" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>2 Apr 2013</time></p>
	<h2><a href="#">The ITPL means more work – and money – for world's top tennis players</a></h2>
</article>	