<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>10 Mar 2013</time></p>
	<h2><a href="#">Two apps that will transform your life</a></h2>
</article>
<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>3 Mar 2013</time></p>
	<h2><a href="#">Three unusual birthday wishes</a></h2>
</article>
<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>24 Feb 2013</time></p>
	<h2><a href="#">I know in my bones that a robot is going to kill you – the new micro-drones</a></h2>
</article>
<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>17 Feb 2013</time></p>
	<h2><a href="#">On the downside: bad meat and angry meteors. On the upside: awesome footage</a></h2>
</article>
<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>27 Jan 2013</time></p>
	<h2><a href="#">Justin Bieber: teen pop idols never die – they're gradually unfollowed</a></h2>
</article>
<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>17 Dec 2012</time></p>
	<h2><a href="#">The Newtown shooting makes us feel helpless. We don't need to be</a></h2>
</article>
<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>16 Dec 2012</time></p>
	<h2><a href="#">Fifteen-minute meals and breakdancing mice: the gifts of Christmas future</a></h2>
</article>
<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>9 Dec 2012</time></p>
	<h2><a href="#">Q: What do Skyfall, The Dark Knight Rises and a hamburger have in common? A: See below</a></h2>
</article>
<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>2 Dec 2012</time></p>
	<h2><a href="#">Wake up, little one. Wake up and witness the terrifying face of Balok</a></h2>
</article>
<article class="article article-news" data-importance="small" data-has-picture="false">
	<p class="date-stamp"><time>25 Nov 2012</time></p>
	<h2><a href="#">2012's Christmas adverts: horrible singers, horny snowmen and horrendous slave labour</a></h2>
</article>
